#!/usr/bin/env bash

APP=$1

source "$(dirname $0)/vars"

# Exit if NGINX_CACHE isn't enabled
if [[ ! -d $DOKKU_ROOT/$APP/NGINX_CACHE ]]; then
	exit 0
fi

NGINX_CONF=$DOKKU_ROOT/$APP/nginx.conf

CACHE_ZONE=cache-$APP

CACHE_PATH="proxy_cache_path $CACHE_DIR keys_zone=$CACHE_ZONE:10m;"
read -r -d '' CACHE_OPTIONS <<EOF
    proxy_cache $CACHE_ZONE;
    proxy_cache_valid 200 300 301 10m;
    proxy_cache_valid any 1m;
EOF

# Edit the Nginx config
export CACHE_OPTIONS
cat - $NGINX_CONF <<< $CACHE_PATH |
	perl -ne 's/(proxy_pass.*$)/$1\n    $ENV{"CACHE_OPTIONS"}/;print' > /tmp/nginx.conf.$$

mv /tmp/nginx.conf.$$ $NGINX_CONF
